version: '3.8'

services:
  francis-nginx:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "8976:80"
      - "8977:443"
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html

  database:
    image: mariadb
    restart: always
    ports:
      - "6969:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: php_dp
  
  #adminer:
   # image: adminer
    #restart: always
    #ports: 
     # -"6969:8080"


volumes:
  data: